# Generated by Django 3.0.8 on 2020-12-22 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('cat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('sub_cat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_cat_name', models.CharField(blank=True, max_length=50, null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.product')),
            ],
            options={
                'db_table': 'sub_category',
            },
        ),
    ]
