# Generated by Django 3.0.8 on 2020-12-22 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_category_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_category',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='cat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.category'),
        ),
        migrations.AddField(
            model_name='sub_category',
            name='cat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.category'),
        ),
    ]
