# Generated by Django 3.0.4 on 2021-01-22 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_product_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
