# Generated by Django 3.0.4 on 2021-01-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
