# Generated by Django 3.0.4 on 2021-01-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20210125_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcart',
            name='product_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
