# Generated by Django 3.0.4 on 2021-01-25 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_addcart_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcart',
            name='brand_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.brand'),
        ),
        migrations.AddField(
            model_name='addcart',
            name='cat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.category'),
        ),
        migrations.AddField(
            model_name='addcart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='addcart',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
