# Generated by Django 3.0.4 on 2021-01-25 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20210125_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcart',
            name='brand_id',
        ),
        migrations.RemoveField(
            model_name='addcart',
            name='cat_id',
        ),
        migrations.RemoveField(
            model_name='addcart',
            name='product_id',
        ),
    ]
